account/urls.py
from django.urls import path
from .views import LoginView, LogoutView, RegistrationView


app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login_url'),
    path('logout/', LogoutView.as_view(), name='logout_url'),
    path('registration/', RegistrationView.as_view(), name='registration_url'),
]

blog/urls.py
from django.urls import path, include
from blog import views
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('', views.PostsList.as_view(), name='posts_list_url'),
    
    path('posts/page/<int:page_number>/', views.PostsList.as_view(), name='posts_list_page_url'),
    path('post/create/', views.PostCreate.as_view(), name='post_create_url'),
    path('post/<str:slug>/update/', views.PostUpdate.as_view(), name='post_update_url'),
    path('post/<str:slug>/', views.PostDetail.as_view(), name='post_detail_url'),
    path('post/<str:slug>/delete/', views.PostDelete.as_view(), name='post_delete_url'),

    path('tags/', views.TagsList.as_view(), name='tags_list_url'),
    path('tag/create/', views.TagCreate.as_view(), name='tag_create_url'),
    path('tag/<str:slug>/update/', views.TagUpdate.as_view(), name='tag_update_url'),
    path('tag/<str:slug>/', views.TagDetail.as_view(), name='tag_detail_url'),
    path('tag/<str:slug>/delete/', views.TagDelete.as_view(), name='tag_delete_url'),
]

blog_engine/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('blog.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>
        {% block title %}
            Blog engine
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'posts_list_url' %}">Посты</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'tags_list_url' %}">Теги</a>
                </li>
                <li class="nav-item active">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'account:logout_url' %}"><b>{{ request.user.username }}</b> Выйти</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'account:login_url' %}">Войти</a>
                    {% endif %}
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Поиск по заголовку и телу поста" aria-label="Search" name="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
            </form>
        </div>
    </nav>

    <div class="container mt-5">
        <div class="row">
            <div class="col-6 offset-md-2">
                {% block content %}
                    There is no any content
                {% endblock %}

                {% if is_paginated %}
                    <nav aria-label="...">
                        <ul class="pagination">
    
                            <li class="page-item {% if not page.has_previous %} disabled {% endif %}">
                                <a class="page-link" href="{% url 'posts_list_page_url' page.number|add:-1 %}" tabindex="-1">Назад</a>
                            </li>
                            
                            {% for page_number in page.paginator.page_range %}
                                {% if page.number == page_number %}
                                    <li class="page-item active">
                                        <a class="page-link" href="{% url 'posts_list_page_url' page_number %}">{{ page_number }}
                                            <span class="sr-only">(current)</span>
                                        </a>
                                    </li>
                                {% elif page.number > page.number|add:-3  and page.number < page.number|add:3 %}
                                    <li class="page-item">
                                        <a class="page-link" href="{% url 'posts_list_page_url' page_number %}">{{ page_number }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
    
                            <li class="page-item {% if not page.has_next %} disabled {% endif %}">
                                <a class="page-link" href="{% url 'posts_list_page_url' page.number|add:1 %}">Вперед</a>
                            </li>
                        </ul>
                    </nav>                
                {% endif %}
            </div>
        </div>
    </div>

    {% if request.user.is_authenticated and request.user.is_staff %}
        <div class="admin-panel">
            <a href="/admin" class="btn btn-outline-info">Админка</a>
            {% block admin-panel %}{% endblock admin-panel %}
        </div>
    {% endif %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>